
services:
  mikroservice.ogrenci.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Adress=http://keycloak:8080/realms/UniversityRealm
      - IdentityOption:Issuer="http://keycloak:8080/realms/UniversityRealm
      - ElasticSearch:BaseUrl=http://elasticsearch.db.log:9200
      - ConnectionStrings:Redis=redis.db.api:6379,password=Password12
      - ConnectionStrings:PostgreSqlServer=Host=postgres.db.ogrenci;Port=5432;Database=ogrenci_db;Username=ogrenci_db_user;Password=ogrenci_db_user_password
      - ConnectionStrings:HangfirePostgreSqlServer=Host=postgres.db.ogrenci;Port=5432;Database=ogrenci_db;Username=ogrenci_db_user;Password=ogrenci_db_user_password
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8080:8080"
    depends_on:
      - redis.db.api
      - postgres.db.ogrenci
    restart: always

  mikroservice.personel.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Adress=http://keycloak:8080/realms/UniversityRealm
      - IdentityOption:Issuer="http://keycloak:8080/realms/UniversityRealm
      - ElasticSearch:BaseUrl=http://elasticsearch.db.log:9200
      - ConnectionStrings:Redis=redis.db.api:6379,password=Password12
      - ConnectionStrings:PostgreSqlServer=Host=postgres.db.personel;Port=5432;Database=personel_db;Username=personel_db_user;Password=personel_db_user_password
      - ConnectionStrings:HangfirePostgreSqlServer=Host=postgres.db.personel;Port=5432;Database=personel_db;Username=personel_db_user;Password=personel_db_user_password
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
    ports:
      - "8082:8080"
    depends_on:
      - redis.db.api
      - postgres.db.personel
    restart: always

  mikroservice.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - IdentityOption:Adress=http://keycloak:8080/realms/UniversityRealm
      - IdentityOption:Issuer=http://keycloak:8080/realms/UniversityRealm
      - ReverseProxy__Clusters__personel__cluster__Destinations__destination1__Address=http://mikroservice.personel.api:8080/
      - ReverseProxy__Clusters__ogrenci__cluster__Destinations__destination1__Address=http://mikroservice.ogrenci.api:8080/
    ports:
      - "8083:8080"
    depends_on:
      - mikroservice.ogrenci.api
      - mikroservice.personel.api
    restart: always
