services:
  prometheus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prometheus.container
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    depends_on:
      - mikroservice.ogrenci.api
      - mikroservice.personel.api
    networks:
      - university-network

  elasticsearch.db.log:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch.db.log
    environment:
     - discovery.type=single-node
     - xpack.security.enabled=false
     - xpack.security.http.ssl.enabled=false
     - ES_JAVA_OPTS=-Xms1g -Xmx1g
     # ÖNEMLİ: Bu satırları EKLEYİN
     - ELASTIC_USERNAME=${ELASTICSEARCH_LOG_USERNAME}
     - ELASTIC_PASSWORD=${ELASTICSEARCH_LOG_PASSWORD}

    ports:
      - "9201:9200"
    volumes:
      - esdatalog:/usr/share/elasticsearch/data
    networks:
      - university-network
   


  kibana.log.ui:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana.log.ui.container
    ports:
      - "5601:5601"
    environment:
    - SERVERNAME=kibana
    - ELASTICSEARCH_HOSTS=http://elasticsearch.db.log:9200
    - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_LOG_USERNAME}  # Tırnakları kaldırın
    - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_LOG_PASSWORD}

    depends_on:
      - elasticsearch.db.log
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:5601 | grep -q '302 Found'"]
      interval: 10s
      timeout: 10s
      retries: 120
    volumes:
      - kibanadata:/usr/share/kibana/data
    networks:
      - university-network

  redis.db.api:
    restart: always
    image: redis:7.0-alpine
    container_name: redis.db.container
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis.db.api.volume:/data
    networks:
      - university-network

  redis.db.api.ui:
    image: rediscommander/redis-commander:latest
    container_name: redis.db.api.ui.container
    restart: always
    depends_on:
      - redis.db.api
    ports:
      - "27033:8081"
    environment:
      REDIS_HOST: redis.db.api
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      HTTP_USER: ${REDIS_UI_USERNAME}
      HTTP_PASSWORD: ${REDIS_UI_PASSWORD}
    networks:
      - university-network

  rabbitmq:
    restart: always
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq.container
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - university-network

  elasticsearch.db.Jaeger:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch.db.Jaeger.container
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTICSEARCH_JAEGER_USERNAME}
      - ELASTIC_PASSWORD=${ELASTICSEARCH_JAEGER_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdatajaeger:/usr/share/elasticsearch/data
    networks:
      - university-network

    #Jaeger
  jaeger:
    restart: always
    container_name: jaeger.container
    image: jaegertracing/jaeger:2.16.0
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch.db.Jaeger:9200
      - ES_USERNAME=${ELASTICSEARCH_JAEGER_USERNAME}
      - ES_PASSWORD=${ELASTICSEARCH_JAEGER_PASSWORD}
      - ES_INDEX_PREFIX=jaeger
      - LOG_LEVEL=info
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" #UI
      - "4317:4317" #Jaeger gRPC
      - "4318:4318" #Jaeger HTTP
      - "5778:5778" #Jaeger agent HTTP
      - "9411:9411" #Jaeger collector HTTP
    depends_on:
      - elasticsearch.db.Jaeger
    volumes:
      - jaeger.data.volume:/opt/jaeger/data
    networks:
      - university-network
  postgres.db.yonetici:
    restart: always
    image: postgres:16.2
    container_name: postgres.db.yonetici.container
    environment:
      POSTGRES_DB: ${POSTGRES_DB_Yonetici}
      POSTGRES_USER: ${POSTGRES_USER_Yonetici}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_Yonetici}
    ports:
      - "5433:5432"
    volumes:
      -  postgres.db.yonetici.volume:/var/lib/postgresql/data
    networks:
      - university-network
  postgres.db.ogrenci:
    restart: always
    image: postgres:16.2
    container_name: postgres.db.ogrenci.container
    environment:
      POSTGRES_DB: ${POSTGRES_DB_Ogrenci}
      POSTGRES_USER: ${POSTGRES_USER_Ogrenci}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_Ogrenci}
    ports:
      - "5434:5432"
    volumes:
      -  postgres.db.ogrenci.volume:/var/lib/postgresql/data
    networks:
      - university-network

  postgres.db.personel:
    restart: always
    image: postgres:16.2
    container_name: postgres.db.personel.container
    environment:
      POSTGRES_DB: ${POSTGRES_DB_Personel}
      POSTGRES_USER: ${POSTGRES_USER_Personel}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_Personel}
    ports:
      - "5435:5432"
    volumes:
      -  postgres.db.personel.volume:/var/lib/postgresql/data
    networks:
      - university-network

  #Postgres & Keycloak
  keycloak:
    restart: always
    container_name: keycloak.container
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev
    environment:
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT_HTTP: false
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB_URL: jdbc:postgresql://postgres.db.keycloak/${POSTGRES_DB_Keycloak}
      KC_DB_USERNAME: ${POSTGRES_USER_Keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD_Keycloak}
    ports:
      - "8081:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data  
    depends_on:
      - postgres.db.keycloak
    networks:
      - university-network

  postgres.db.keycloak:
    restart: always
    image: postgres:16.2
    container_name: postgres.db.keycloak.container
    environment:
      POSTGRES_DB: ${POSTGRES_DB_Keycloak}
      POSTGRES_USER: ${POSTGRES_USER_Keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_Keycloak}
    ports:
      - "5436:5432"
    volumes:
      -  postgres.db.keycloak.volume:/var/lib/postgresql/data
    networks:
      - university-network

  postgres.db.ui:
    restart: always
    image: dpage/pgadmin4
    container_name: postgres.db.ui.container
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - postgres.db.ui.data:/var/lib/pgadmin
    networks:
      - university-network

  mikroservice.ogrenci.api:
    image: ${DOCKER_REGISTRY-}mikroserviceogrenciapi
    build:
      context: .
      dockerfile: Mikroservice.Ogrenci.Api/Dockerfile
    networks:
      - university-network

  mikroservice.personel.api:
    image: ${DOCKER_REGISTRY-}mikroservicepersonelapi
    build:
      context: .
      dockerfile: Mikroservice.Personel.Api/Dockerfile
    networks:
      - university-network

  mikroservice.gateway:
    image: ${DOCKER_REGISTRY-}mikroservicegateway
    build:
      context: .
      dockerfile: Mikroservice.Gateway/Dockerfile
    networks:
      - university-network

  microservice.yonetici.api:
    image: ${DOCKER_REGISTRY-}microserviceyoneticiapi
    build:
      context: .
      dockerfile: Microservice.Yonetici.Api/Dockerfile
    networks:
      - university-network
volumes:
  jaeger.data.volume:
  postgres.db.keycloak.volume:
  postgres.db.ui.data:
  keycloak-data:
  postgres.db.ogrenci.volume:  
  postgres.db.personel.volume:
  postgres.db.yonetici.volume: 
  esdatajaeger:
  redis.db.api.volume:    
  rabbitmq_data:
  esdatalog:
  kibanadata:
  prometheus_data:

networks:
  university-network:
    driver: bridge
