// <auto-generated />
using System;
using Microservice.Site.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mikroservice.Site.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514130028_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Site.Domain.Entities.YonetimDuyuru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("YonetimDuyurular");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.BandLogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("DilId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("SiteId");

                    b.ToTable("BandLogos");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ad");

                    b.HasIndex("ParentId");

                    b.HasIndex("Sira");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Dil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InternationalAd")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Diller");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Hedef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Hedefler");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Icerik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BaslamaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DilId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EklemeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("GosterimSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("HedefId")
                        .HasColumnType("integer");

                    b.Property<string>("IcerikMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("text");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text");

                    b.Property<string>("SeoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<int>("Tip")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YayimTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("HedefId");

                    b.HasIndex("SiteId", "DilId");

                    b.HasIndex("SiteId", "SeoUrl")
                        .IsUnique();

                    b.ToTable("Icerik");

                    b.HasDiscriminator<int>("Tip");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DilId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("SiteId");

                    b.ToTable("MediaFile");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DilId")
                        .HasColumnType("integer");

                    b.Property<int>("HedefId")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("MegaMenu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("HedefId");

                    b.HasIndex("ParentId", "Sira");

                    b.HasIndex("SiteId", "DilId");

                    b.ToTable("Menuler");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.PersonelTelefon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SitePersonelId")
                        .HasColumnType("integer");

                    b.Property<string>("TelefonNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SitePersonelId");

                    b.ToTable("PersonelTelefonlar");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.PersonelTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique();

                    b.ToTable("PersonelTipleri");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Popup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BaslamaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("CookieIleTekrarGosterme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("EklemeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("GosterimSayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GosterimSuresiSaniye")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("IcerikMetni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("text");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text");

                    b.Property<string>("SeoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<bool>("TamEkranMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("YayimTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("Popuplar");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SikcaSorulanSoru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cevap")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DilId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("SeoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DilId");

                    b.HasIndex("SeoUrl");

                    b.HasIndex("ParentId", "Sira");

                    b.HasIndex("SiteId", "DilId");

                    b.ToTable("SikcaSorulanSorular");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SiteAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SiteAdiEng")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SiteAlanAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SiteEPosta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SiteEPostaHost")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SiteEPostaPort")
                        .HasColumnType("integer");

                    b.Property<string>("SiteEPostaSifre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SiteUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TemplateId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Siteler");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SiteOzellikleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SiteAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteAdressEng")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteBaslangicHakkimizda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteBaslangicHakkimizdaEng")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteBaslangicVideoLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteBaslangicVideoResimAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteFacebookAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteFaxNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SiteFooterLogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteHakkindaLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteHakkindaResim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteHaritaAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("SiteInstagramAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteLinkedinAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteTelNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SiteTopbarLogo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteTwitterAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteVideoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteWatsappAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteYoutubeAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("SiteOzellikleri");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SitePersonel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlogAdress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DeneyimVeCalismalari")
                        .HasColumnType("text");

                    b.Property<string>("FacebookAdress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("GoogleplusAdress")
                        .HasColumnType("text");

                    b.Property<string>("Hakkinda")
                        .HasColumnType("text");

                    b.Property<string>("IlgiAlanlari")
                        .HasColumnType("text");

                    b.Property<string>("InstagramAdress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<int>("PersonelTipId")
                        .HasColumnType("integer");

                    b.Property<string>("ResimUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.Property<string>("TwitterAdress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("UnvanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonelTipId");

                    b.HasIndex("UnvanId");

                    b.HasIndex("SiteId", "PersonelId")
                        .IsUnique();

                    b.ToTable("SitePersonelleri");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Template", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FolderName")
                        .HasColumnType("text");

                    b.Property<string>("LayoutPath")
                        .HasColumnType("text");

                    b.Property<string>("TemplateAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TemplateTuru")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Templateler");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Unvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("KisaAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.Property<int>("TipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Ad");

                    b.HasIndex("KisaAd");

                    b.HasIndex("ParentId");

                    b.HasIndex("Sira");

                    b.HasIndex("TipId");

                    b.ToTable("Unvanlar");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.YoneticiSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KeycloakUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "KeycloakUserId");

                    b.ToTable("YoneticiSiteler");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Banner", b =>
                {
                    b.HasBaseType("Mikroservice.Site.Domain.Entities.Icerik");

                    b.Property<int>("Sira")
                        .HasColumnType("integer");

                    b.HasIndex("SiteId", "Sira");

                    b.HasDiscriminator().HasValue(6);
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Bilgi", b =>
                {
                    b.HasBaseType("Mikroservice.Site.Domain.Entities.Icerik");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Duyuru", b =>
                {
                    b.HasBaseType("Mikroservice.Site.Domain.Entities.Icerik");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Etkinlik", b =>
                {
                    b.HasBaseType("Mikroservice.Site.Domain.Entities.Icerik");

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Haber", b =>
                {
                    b.HasBaseType("Mikroservice.Site.Domain.Entities.Icerik");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Video", b =>
                {
                    b.HasBaseType("Mikroservice.Site.Domain.Entities.Icerik");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasDiscriminator().HasValue(5);
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.BandLogo", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("BandLogos")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Birim", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Birim", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Icerik", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Hedef", "Hedef")
                        .WithMany()
                        .HasForeignKey("HedefId");

                    b.Navigation("Dil");

                    b.Navigation("Hedef");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("MediaFiles")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Menu", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Hedef", "Hedef")
                        .WithMany()
                        .HasForeignKey("HedefId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Menu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("Menus")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Hedef");

                    b.Navigation("Parent");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.PersonelTelefon", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.SitePersonel", "SitePersonel")
                        .WithMany("PersonelTelefons")
                        .HasForeignKey("SitePersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SitePersonel");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Popup", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithOne("Popup")
                        .HasForeignKey("Mikroservice.Site.Domain.Entities.Popup", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SikcaSorulanSoru", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Dil", "Dil")
                        .WithMany()
                        .HasForeignKey("DilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.SikcaSorulanSoru", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("SikcaSorulanSorus")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dil");

                    b.Navigation("Parent");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Site", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Birim", "Birim")
                        .WithMany("Sites")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Template", "Template")
                        .WithMany("Sites")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SiteOzellikleri", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithOne("SiteOzellikleri")
                        .HasForeignKey("Mikroservice.Site.Domain.Entities.SiteOzellikleri", "SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SitePersonel", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.PersonelTip", "PersonelTip")
                        .WithMany("SitePersonels")
                        .HasForeignKey("PersonelTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("SitePersonels")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mikroservice.Site.Domain.Entities.Unvan", "Unvan")
                        .WithMany("SitePersonels")
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PersonelTip");

                    b.Navigation("Site");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Unvan", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Unvan", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Mikroservice.Site.Domain.Entities.PersonelTip", "PersonelTip")
                        .WithMany("Unvans")
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("PersonelTip");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.YoneticiSite", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("YoneticiSites")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Banner", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Bilgi", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Duyuru", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("Duyurus")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Etkinlik", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Haber", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany("Habers")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Video", b =>
                {
                    b.HasOne("Mikroservice.Site.Domain.Entities.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Birim", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Menu", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.PersonelTip", b =>
                {
                    b.Navigation("SitePersonels");

                    b.Navigation("Unvans");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SikcaSorulanSoru", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Site", b =>
                {
                    b.Navigation("BandLogos");

                    b.Navigation("Duyurus");

                    b.Navigation("Habers");

                    b.Navigation("MediaFiles");

                    b.Navigation("Menus");

                    b.Navigation("Popup");

                    b.Navigation("SikcaSorulanSorus");

                    b.Navigation("SiteOzellikleri")
                        .IsRequired();

                    b.Navigation("SitePersonels");

                    b.Navigation("YoneticiSites");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.SitePersonel", b =>
                {
                    b.Navigation("PersonelTelefons");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Template", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("Mikroservice.Site.Domain.Entities.Unvan", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("SitePersonels");
                });
#pragma warning restore 612, 618
        }
    }
}
