// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikroservice.Ogrenci.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mikroservice.Ogrenci.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402132322_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Ogrenci.Domain.Entities.Ogrenci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("AkademikProgram")
                        .HasColumnType("text");

                    b.Property<string>("AnaAdi")
                        .HasColumnType("text");

                    b.Property<string>("BabaAdi")
                        .HasColumnType("text");

                    b.Property<string>("Bolum")
                        .HasColumnType("text");

                    b.Property<int?>("BolumId")
                        .HasColumnType("integer");

                    b.Property<string>("BolumIngilizceAdi")
                        .HasColumnType("text");

                    b.Property<string>("Cinsiyeti")
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .HasColumnType("text");

                    b.Property<string>("DurumDetail")
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .HasColumnType("text");

                    b.Property<string>("Fakulte")
                        .HasColumnType("text");

                    b.Property<int?>("FakulteId")
                        .HasColumnType("integer");

                    b.Property<string>("FakulteIngilizceAdi")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IlisikKesmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KanGrubu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KisiselEposta")
                        .HasColumnType("text");

                    b.Property<string>("KisiselTelefon")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MezuniyetTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("OgrenciProgramId")
                        .HasColumnType("integer");

                    b.Property<string>("OgretimTipi")
                        .HasColumnType("text");

                    b.Property<string>("PersonBase64Image")
                        .HasColumnType("text");

                    b.Property<string>("ProgramTipi")
                        .HasColumnType("text");

                    b.Property<string>("ProgramTuru")
                        .HasColumnType("text");

                    b.Property<string>("ResimKodu")
                        .HasColumnType("text");

                    b.Property<string>("Scholarship")
                        .HasColumnType("text");

                    b.Property<string>("SehitGaziYakini")
                        .HasColumnType("text");

                    b.Property<int?>("Sinif")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SonGuncellemeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyadi")
                        .HasColumnType("text");

                    b.Property<string>("StudentNo")
                        .HasColumnType("text");

                    b.Property<string>("TcNumarasi")
                        .HasColumnType("text");

                    b.Property<string>("TelefonCep")
                        .HasColumnType("text");

                    b.Property<decimal?>("TranscriptNotOrtalamasi")
                        .HasColumnType("numeric");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("Uyruk")
                        .HasColumnType("text");

                    b.Property<int?>("YoksisId")
                        .HasColumnType("integer");

                    b.Property<int?>("YoksisOgrenciId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Eposta");

                    b.HasIndex("OgrenciProgramId");

                    b.HasIndex("SonGuncellemeTarihi");

                    b.HasIndex("Username");

                    b.HasIndex("Adi", "Soyadi");

                    b.ToTable("Ogrencis");
                });
#pragma warning restore 612, 618
        }
    }
}
