// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikroservice.Ogrenci.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mikroservice.Ogrenci.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Ogrenci.Domain.Entities.Ogrenci", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("adi")
                        .HasColumnType("text");

                    b.Property<string>("adres")
                        .HasColumnType("text");

                    b.Property<string>("akademikprogram")
                        .HasColumnType("text");

                    b.Property<string>("anaadi")
                        .HasColumnType("text");

                    b.Property<string>("babaadi")
                        .HasColumnType("text");

                    b.Property<string>("bolum")
                        .HasColumnType("text");

                    b.Property<int?>("bolumid")
                        .HasColumnType("integer");

                    b.Property<string>("bolumingilizceadi")
                        .HasColumnType("text");

                    b.Property<string>("cinsiyeti")
                        .HasColumnType("text");

                    b.Property<DateTime>("dogumtarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("dogumyeri")
                        .HasColumnType("text");

                    b.Property<string>("durum")
                        .HasColumnType("text");

                    b.Property<string>("eposta")
                        .HasColumnType("text");

                    b.Property<string>("fakulte")
                        .HasColumnType("text");

                    b.Property<int?>("fakulteid")
                        .HasColumnType("integer");

                    b.Property<string>("fakulteingilizceadi")
                        .HasColumnType("text");

                    b.Property<string>("kangrubu")
                        .HasColumnType("text");

                    b.Property<DateTime>("kayittarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("kisiseleposta")
                        .HasColumnType("text");

                    b.Property<string>("kisiseltelefon")
                        .HasColumnType("text");

                    b.Property<int>("ogrenciprogramid")
                        .HasColumnType("integer");

                    b.Property<string>("ogretimtipi")
                        .HasColumnType("text");

                    b.Property<string>("personbase64image")
                        .HasColumnType("text");

                    b.Property<string>("programtipi")
                        .HasColumnType("text");

                    b.Property<string>("programturu")
                        .HasColumnType("text");

                    b.Property<string>("resimkodu")
                        .HasColumnType("text");

                    b.Property<string>("scholarship")
                        .HasColumnType("text");

                    b.Property<string>("sehitgaziyakini")
                        .HasColumnType("text");

                    b.Property<int?>("sinif")
                        .HasColumnType("integer");

                    b.Property<DateTime>("songuncellemetarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("soyadi")
                        .HasColumnType("text");

                    b.Property<string>("studentno")
                        .HasColumnType("text");

                    b.Property<string>("tcnumarasi")
                        .HasColumnType("text");

                    b.Property<string>("telefoncep")
                        .HasColumnType("text");

                    b.Property<decimal?>("transcriptnotortalamasi")
                        .HasColumnType("numeric");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.Property<string>("uyruk")
                        .HasColumnType("text");

                    b.Property<int?>("yoksisid")
                        .HasColumnType("integer");

                    b.Property<int?>("yoksisogrenciid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Ogrencis");
                });
#pragma warning restore 612, 618
        }
    }
}
