// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikroservice.Personel.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mikroservice.Personel.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409114157_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Personel.Domain.Entities.Personel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .HasColumnType("text");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<bool?>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("AnaAdi")
                        .HasColumnType("text");

                    b.Property<string>("Asili")
                        .HasColumnType("text");

                    b.Property<string>("AsliUnvan")
                        .HasColumnType("text");

                    b.Property<string>("BabaAdi")
                        .HasColumnType("text");

                    b.Property<decimal?>("BrutUcret")
                        .HasColumnType("numeric");

                    b.Property<string>("Cinsiyeti")
                        .HasColumnType("text");

                    b.Property<bool?>("CovidBagisik")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DogumTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DogumYeri")
                        .HasColumnType("text");

                    b.Property<int?>("EkGosterge")
                        .HasColumnType("integer");

                    b.Property<string>("EmekliSicilKodu")
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .HasColumnType("text");

                    b.Property<string>("GorevUnvan")
                        .HasColumnType("text");

                    b.Property<int?>("GorevUnvaniId")
                        .HasColumnType("integer");

                    b.Property<string>("GorevYeri")
                        .HasColumnType("text");

                    b.Property<int?>("GorevYeriId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GoreveBaslamaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HesDurumu")
                        .HasColumnType("text");

                    b.Property<string>("IdariGorevler")
                        .HasColumnType("text");

                    b.Property<string>("IliskiliOlduguPozisyonlar")
                        .HasColumnType("text");

                    b.Property<int?>("KadroBirimId")
                        .HasColumnType("integer");

                    b.Property<string>("KadroBirimi")
                        .HasColumnType("text");

                    b.Property<string>("KadroKodu")
                        .HasColumnType("text");

                    b.Property<string>("KadroTipi")
                        .HasColumnType("text");

                    b.Property<int?>("KadroTipiId")
                        .HasColumnType("integer");

                    b.Property<string>("KadroUnvan")
                        .HasColumnType("text");

                    b.Property<int?>("KadroUnvanId")
                        .HasColumnType("integer");

                    b.Property<string>("KadroUstBirim")
                        .HasColumnType("text");

                    b.Property<int?>("KadroUstBirimId")
                        .HasColumnType("integer");

                    b.Property<string>("KanGrubu")
                        .HasColumnType("text");

                    b.Property<string>("KisiselEposta")
                        .HasColumnType("text");

                    b.Property<string>("KisiselTelefon")
                        .HasColumnType("text");

                    b.Property<string>("KurumSicilNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("KurumdanAyrilisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PersonBase64Image")
                        .HasColumnType("text");

                    b.Property<string>("PersonBase64ImageModifiedOn")
                        .HasColumnType("text");

                    b.Property<string>("PersonEncryptedId")
                        .HasColumnType("text");

                    b.Property<int?>("PersonId")
                        .HasColumnType("integer");

                    b.Property<string>("PersonelTipi")
                        .HasColumnType("text");

                    b.Property<int?>("PersonelTipiId")
                        .HasColumnType("integer");

                    b.Property<string>("SehitGaziYakini")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonGuncellemeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SonTestZamani")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyadi")
                        .HasColumnType("text");

                    b.Property<string>("TcNumarasi")
                        .HasColumnType("text");

                    b.Property<string>("TelefonCep")
                        .HasColumnType("text");

                    b.Property<string>("TelefonDahili")
                        .HasColumnType("text");

                    b.Property<string>("TelefonDahiliNumara")
                        .HasColumnType("text");

                    b.Property<int?>("UnvanId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<string>("UstGorevBirimAdi")
                        .HasColumnType("text");

                    b.Property<int?>("UstGorevBirimId")
                        .HasColumnType("integer");

                    b.Property<string>("UstGorevYeriAdi")
                        .HasColumnType("text");

                    b.Property<int?>("UstGorevYeriId")
                        .HasColumnType("integer");

                    b.Property<string>("Uyruk")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Eposta");

                    b.HasIndex("SonGuncellemeTarihi");

                    b.HasIndex("Username");

                    b.HasIndex("Adi", "Soyadi");

                    b.ToTable("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
