// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mikroservice.Personel.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mikroservice.Personel.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microservice.Personel.Domain.Entities.Personel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("adres")
                        .HasColumnType("text");

                    b.Property<bool?>("aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("anaadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("asili")
                        .HasColumnType("text");

                    b.Property<string>("asliunvan")
                        .HasColumnType("text");

                    b.Property<string>("babaadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("brutucret")
                        .HasColumnType("numeric");

                    b.Property<string>("cinsiyeti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("dogumtarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("dogumyeri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ekgosterge")
                        .HasColumnType("integer");

                    b.Property<string>("emeklisicilkodu")
                        .HasColumnType("text");

                    b.Property<string>("eposta")
                        .HasColumnType("text");

                    b.Property<DateTime?>("gorevebaslamatarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("gorevunvan")
                        .HasColumnType("text");

                    b.Property<int?>("gorevunvaniid")
                        .HasColumnType("integer");

                    b.Property<string>("gorevyeri")
                        .HasColumnType("text");

                    b.Property<int?>("gorevyeriid")
                        .HasColumnType("integer");

                    b.Property<string>("idarigorevler")
                        .HasColumnType("text");

                    b.Property<string>("iliskilioldugupozisyonlar")
                        .HasColumnType("text");

                    b.Property<string>("kadrobirimi")
                        .HasColumnType("text");

                    b.Property<int?>("kadrobirimid")
                        .HasColumnType("integer");

                    b.Property<string>("kadrokodu")
                        .HasColumnType("text");

                    b.Property<string>("kadrotipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("kadrotipiid")
                        .HasColumnType("integer");

                    b.Property<string>("kadrounvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("kadrounvanid")
                        .HasColumnType("integer");

                    b.Property<string>("kadroustbirim")
                        .HasColumnType("text");

                    b.Property<int?>("kadroustbirimid")
                        .HasColumnType("integer");

                    b.Property<string>("kangrubu")
                        .HasColumnType("text");

                    b.Property<string>("kisiseleposta")
                        .HasColumnType("text");

                    b.Property<string>("kisiseltelefon")
                        .HasColumnType("text");

                    b.Property<DateTime?>("kurumdanayrilistarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("kurumsicilno")
                        .HasColumnType("text");

                    b.Property<string>("personbase64image")
                        .HasColumnType("text");

                    b.Property<string>("personbase64imagemodifiedon")
                        .HasColumnType("text");

                    b.Property<string>("personeltipi")
                        .HasColumnType("text");

                    b.Property<int?>("personeltipiid")
                        .HasColumnType("integer");

                    b.Property<string>("personencryptedid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("personid")
                        .HasColumnType("integer");

                    b.Property<string>("sehitgaziyakini")
                        .HasColumnType("text");

                    b.Property<DateTime?>("songuncellemetarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("soyadi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tcnumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefoncep")
                        .HasColumnType("text");

                    b.Property<string>("telefondahili")
                        .HasColumnType("text");

                    b.Property<string>("telefondahilinumara")
                        .HasColumnType("text");

                    b.Property<int?>("unvanid")
                        .HasColumnType("integer");

                    b.Property<string>("username")
                        .HasColumnType("text");

                    b.Property<string>("ustgorevbirimadi")
                        .HasColumnType("text");

                    b.Property<int?>("ustgorevbirimid")
                        .HasColumnType("integer");

                    b.Property<string>("ustgorevyeriadi")
                        .HasColumnType("text");

                    b.Property<int?>("ustgorevyeriid")
                        .HasColumnType("integer");

                    b.Property<string>("uyruk")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("eposta");

                    b.HasIndex("songuncellemetarihi");

                    b.HasIndex("username");

                    b.HasIndex("adi", "soyadi");

                    b.ToTable("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
